import { ServicePreset, ThemeId, Service } from '../types';

export interface ThemeConfig {
  id: ThemeId;
  name: string;
  emoji: string;
  tagline: string;
  accent: string;
  sidebarBg: string;
  appBg: string;
  activePill: string;
  border: string;
  previewColors: string[];
}

export const THEMES: Record<ThemeId, ThemeConfig> = {
  sakura: {
    id: 'sakura',
    name: 'Blush Sakura',
    emoji: '🌸',
    tagline: 'Cherry blossom petals & soft rose morning light',
    accent: '#F48498',
    sidebarBg: 'bg-rose-50/70',
    appBg: 'bg-gradient-to-br from-[#FFF5F6] via-[#FFFBFB] to-[#FDE8EC]',
    activePill: 'bg-pastel-sakura-100/90 text-pastel-sakura-600 border border-pastel-sakura-300/40 shadow-sm',
    border: 'border-rose-100/80',
    previewColors: ['#FFB7C5', '#FDE2E4', '#F48498', '#FFF5F5'],
  },
  lavender: {
    id: 'lavender',
    name: 'Lavender Mist',
    emoji: '🪻',
    tagline: 'Ethereal lilac haze, soft periwinkle, and peaceful focus',
    accent: '#A194F7',
    sidebarBg: 'bg-violet-50/70',
    appBg: 'bg-gradient-to-br from-[#F8F7FF] via-[#FCFBFF] to-[#EFEAFF]',
    activePill: 'bg-pastel-lavender-100/90 text-pastel-lavender-600 border border-pastel-lavender-300/40 shadow-sm',
    border: 'border-purple-100/80',
    previewColors: ['#BDB2FF', '#EFEAFF', '#8A7BEF', '#F8F7FF'],
  },
  matcha: {
    id: 'matcha',
    name: 'Matcha & Sage',
    emoji: '🍵',
    tagline: 'Calm Japanese tea gardens, soft eucalyptus and clarity',
    accent: '#70A288',
    sidebarBg: 'bg-emerald-50/60',
    appBg: 'bg-gradient-to-br from-[#F5FAF7] via-[#FAFCFB] to-[#E2F0E8]',
    activePill: 'bg-pastel-matcha-100/90 text-pastel-matcha-600 border border-pastel-matcha-300/40 shadow-sm',
    border: 'border-emerald-100/70',
    previewColors: ['#8EB69B', '#E2F0E8', '#538D6D', '#F5FAF7'],
  },
  nordic: {
    id: 'nordic',
    name: 'Nordic Breeze',
    emoji: '🌊',
    tagline: 'Serene Scandinavian fjords, crisp air, and glacier sky',
    accent: '#00B4D8',
    sidebarBg: 'bg-sky-50/70',
    appBg: 'bg-gradient-to-br from-[#F3FAFC] via-[#F8FDFF] to-[#E1F5FE]',
    activePill: 'bg-pastel-nordic-100/90 text-pastel-nordic-600 border border-pastel-nordic-300/40 shadow-sm',
    border: 'border-sky-100/80',
    previewColors: ['#90E0EF', '#E1F5FE', '#00B4D8', '#CAF0F8'],
  },
  buttercup: {
    id: 'buttercup',
    name: 'Buttercup Vanilla',
    emoji: '🍯',
    tagline: 'Warm golden hour sunlight, lemon cream, and honey drops',
    accent: '#F6B93B',
    sidebarBg: 'bg-amber-50/60',
    appBg: 'bg-gradient-to-br from-[#FFFCF2] via-[#FFFDF7] to-[#FFF3CD]',
    activePill: 'bg-pastel-buttercup-100/90 text-pastel-buttercup-600 border border-pastel-buttercup-300/40 shadow-sm',
    border: 'border-amber-100/80',
    previewColors: ['#FFEAA7', '#FFF8E1', '#FAD02C', '#FFFCF2'],
  },
  noir: {
    id: 'noir',
    name: 'Pastel Noir',
    emoji: '🌌',
    tagline: 'Deep velvet night with iridescent pastel luminescent glow',
    accent: '#BDB2FF',
    sidebarBg: 'bg-[#141620]/90',
    appBg: 'bg-[#0E1017]',
    activePill: 'bg-[#252837] text-purple-200 border border-purple-500/20 shadow-md',
    border: 'border-zinc-800/80',
    previewColors: ['#1A1C26', '#BDB2FF', '#8EB69B', '#2C3044'],
  },
};

export const SERVICE_PRESETS: ServicePreset[] = [
  {
    type: 'whatsapp',
    name: 'WhatsApp',
    description: 'WhatsApp Web - Chat, voice notes & media',
    defaultUrl: 'https://web.whatsapp.com',
    defaultColor: '#25D366',
    badgeTag: 'Personal',
    category: 'chat',
    supportsMultiple: true,
  },
  {
    type: 'whatsapp_business',
    name: 'WhatsApp Business',
    description: 'WhatsApp Business - Dedicated work partition',
    defaultUrl: 'https://web.whatsapp.com',
    defaultColor: '#128C7E',
    badgeTag: 'Business',
    category: 'chat',
    supportsMultiple: true,
  },
  {
    type: 'telegram',
    name: 'Telegram',
    description: 'Fast, secure messaging & channels',
    defaultUrl: 'https://web.telegram.org/a/',
    defaultColor: '#2AABEE',
    badgeTag: 'Cloud',
    category: 'chat',
    supportsMultiple: true,
  },
  {
    type: 'signal',
    name: 'Signal Web',
    description: 'Privacy-focused messaging',
    defaultUrl: 'https://signal.org',
    defaultColor: '#3A76F0',
    badgeTag: 'Encrypted',
    category: 'chat',
    supportsMultiple: false,
  },
  {
    type: 'slack',
    name: 'Slack',
    description: 'Channels, team messaging & huddles',
    defaultUrl: 'https://slack.com/signin',
    defaultColor: '#ECB22E',
    badgeTag: 'Team',
    category: 'work',
    supportsMultiple: true,
  },
  {
    type: 'google_chat',
    name: 'Google Chat',
    description: 'Spaces and team direct messages',
    defaultUrl: 'https://mail.google.com/chat/u/0/',
    defaultColor: '#00AC47',
    badgeTag: 'Workspace',
    category: 'work',
    supportsMultiple: true,
  },
  {
    type: 'discord',
    name: 'Discord',
    description: 'Communities, voice channels & chats',
    defaultUrl: 'https://discord.com/app',
    defaultColor: '#5865F2',
    badgeTag: 'Community',
    category: 'chat',
    supportsMultiple: true,
  },
  {
    type: 'messenger',
    name: 'Messenger',
    description: 'Facebook Messenger chats & calls',
    defaultUrl: 'https://www.messenger.com',
    defaultColor: '#0084FF',
    badgeTag: 'Social',
    category: 'chat',
    supportsMultiple: true,
  },
  {
    type: 'chatgpt',
    name: 'ChatGPT',
    description: 'OpenAI conversational assistant',
    defaultUrl: 'https://chatgpt.com',
    defaultColor: '#10A37F',
    badgeTag: 'AI',
    category: 'ai',
    supportsMultiple: true,
  },
  {
    type: 'claude',
    name: 'Claude',
    description: 'Anthropic AI assistant',
    defaultUrl: 'https://claude.ai',
    defaultColor: '#D97706',
    badgeTag: 'AI',
    category: 'ai',
    supportsMultiple: true,
  },
];

export const INITIAL_SERVICES: Service[] = [
  {
    id: 'wa-personal',
    name: 'WhatsApp',
    type: 'whatsapp',
    url: 'https://web.whatsapp.com',
    partition: 'persist:service_wa_personal',
    accountLabel: 'Personal',
    accentColor: '#25D366',
    isMuted: false,
    zoomFactor: 1.0,
    isHibernated: false,
    lastActive: Date.now(),
  },
  {
    id: 'wa-business',
    name: 'WhatsApp Business',
    type: 'whatsapp_business',
    url: 'https://web.whatsapp.com',
    partition: 'persist:service_wa_business',
    accountLabel: 'Business',
    accentColor: '#128C7E',
    isMuted: false,
    zoomFactor: 1.0,
    isHibernated: true,
    lastActive: Date.now() - 3600000,
  },
  {
    id: 'telegram-main',
    name: 'Telegram',
    type: 'telegram',
    url: 'https://web.telegram.org/a/',
    partition: 'persist:service_telegram_main',
    accountLabel: 'Main',
    accentColor: '#2AABEE',
    isMuted: false,
    zoomFactor: 1.0,
    isHibernated: true,
    lastActive: Date.now() - 7200000,
  },
  {
    id: 'slack-work',
    name: 'Slack',
    type: 'slack',
    url: 'https://slack.com/signin',
    partition: 'persist:service_slack_work',
    accountLabel: 'Work',
    accentColor: '#ECB22E',
    isMuted: false,
    zoomFactor: 1.0,
    isHibernated: true,
    lastActive: Date.now() - 10800000,
  },
];
